// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: GUI_v1

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_panelSetting = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_panelSetting, lv_pct(100));
lv_obj_set_height( ui_panelSetting, lv_pct(100));
lv_obj_set_align( ui_panelSetting, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_panelSetting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelSetting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PasswordbtnSetting = lv_imgbtn_create(ui_panelSetting);
lv_imgbtn_set_src(ui_PasswordbtnSetting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_iconpassword_png, NULL);
lv_obj_set_width( ui_PasswordbtnSetting, 50);
lv_obj_set_height( ui_PasswordbtnSetting, 50);
lv_obj_set_x( ui_PasswordbtnSetting, 50 );
lv_obj_set_y( ui_PasswordbtnSetting, 5 );

ui_FPbtnSetting = lv_imgbtn_create(ui_panelSetting);
lv_imgbtn_set_src(ui_FPbtnSetting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_iconfinger_png, NULL);
lv_obj_set_width( ui_FPbtnSetting, 50);
lv_obj_set_height( ui_FPbtnSetting, 50);
lv_obj_set_x( ui_FPbtnSetting, 30 );
lv_obj_set_y( ui_FPbtnSetting, 5 );
lv_obj_set_align( ui_FPbtnSetting, LV_ALIGN_TOP_MID );

ui_CardbtnSetting = lv_imgbtn_create(ui_panelSetting);
lv_imgbtn_set_src(ui_CardbtnSetting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_iconcard_png, NULL);
lv_obj_set_width( ui_CardbtnSetting, 50);
lv_obj_set_height( ui_CardbtnSetting, 50);
lv_obj_set_x( ui_CardbtnSetting, 10 );
lv_obj_set_y( ui_CardbtnSetting, 5 );
lv_obj_set_align( ui_CardbtnSetting, LV_ALIGN_TOP_RIGHT );

ui_Label6 = lv_label_create(ui_panelSetting);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 50 );
lv_obj_set_y( ui_Label6, -8 );
lv_label_set_text(ui_Label6,"Password");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_panelSetting);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 30 );
lv_obj_set_y( ui_Label7, -8 );
lv_obj_set_align( ui_Label7, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label7,"Fingerprint");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_panelSetting);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -3 );
lv_obj_set_y( ui_Label8, -8 );
lv_obj_set_align( ui_Label8, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_Label8,"Card");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomebtnSetting = lv_imgbtn_create(ui_panelSetting);
lv_imgbtn_set_src(ui_HomebtnSetting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_iconhome_png, NULL);
lv_obj_set_width( ui_HomebtnSetting, 50);
lv_obj_set_height( ui_HomebtnSetting, 50);
lv_obj_set_x( ui_HomebtnSetting, -10 );
lv_obj_set_y( ui_HomebtnSetting, 5 );

ui_Label15 = lv_label_create(ui_panelSetting);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -2 );
lv_obj_set_y( ui_Label15, -8 );
lv_label_set_text(ui_Label15,"Home");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OptionPassword = lv_tabview_create(ui_panelSetting, LV_DIR_LEFT, 50);
lv_obj_set_height( ui_OptionPassword, 220);
lv_obj_set_width( ui_OptionPassword, lv_pct(108));
lv_obj_set_x( ui_OptionPassword, 0 );
lv_obj_set_y( ui_OptionPassword, 8 );
lv_obj_set_align( ui_OptionPassword, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_OptionPassword, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_OptionPassword, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OptionPassword, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OptionPassword, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OptionPassword, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OptionPassword, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OptionPassword, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OptionPassword, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_OptionPassword), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_OptionPassword), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_OptionPassword), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_OptionPassword), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_OptionPassword), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_OptionPassword), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_OptionPassword), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_Admin = lv_tabview_add_tab(ui_OptionPassword, "Admin");
lv_obj_set_style_bg_color(ui_Admin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Admin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Admin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Admin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Admin, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AreaCurrentAdmin = lv_textarea_create(ui_Admin);
lv_obj_set_width( ui_AreaCurrentAdmin, lv_pct(100));
lv_obj_set_height( ui_AreaCurrentAdmin, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_AreaCurrentAdmin, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_AreaCurrentAdmin,"Current admin password");
lv_textarea_set_one_line(ui_AreaCurrentAdmin,true);
lv_textarea_set_password_mode(ui_AreaCurrentAdmin, true);



ui_AreaNewAdmin = lv_textarea_create(ui_Admin);
lv_obj_set_width( ui_AreaNewAdmin, lv_pct(100));
lv_obj_set_height( ui_AreaNewAdmin, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaNewAdmin, 1 );
lv_obj_set_y( ui_AreaNewAdmin, -23 );
lv_obj_set_align( ui_AreaNewAdmin, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_AreaNewAdmin,"New admin password");
lv_textarea_set_one_line(ui_AreaNewAdmin,true);
lv_textarea_set_password_mode(ui_AreaNewAdmin, true);



ui_AreaConfirmAdmin = lv_textarea_create(ui_Admin);
lv_obj_set_width( ui_AreaConfirmAdmin, lv_pct(100));
lv_obj_set_height( ui_AreaConfirmAdmin, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaConfirmAdmin, 1 );
lv_obj_set_y( ui_AreaConfirmAdmin, 31 );
lv_obj_set_align( ui_AreaConfirmAdmin, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_AreaConfirmAdmin,"Confirm admin password");
lv_textarea_set_one_line(ui_AreaConfirmAdmin,true);
lv_textarea_set_password_mode(ui_AreaConfirmAdmin, true);



ui_btnChangebtn = lv_btn_create(ui_Admin);
lv_obj_set_width( ui_btnChangebtn, 60);
lv_obj_set_height( ui_btnChangebtn, 35);
lv_obj_set_align( ui_btnChangebtn, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_btnChangebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnChangebtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_btnChangebtn);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Change");

ui_User = lv_tabview_add_tab(ui_OptionPassword, "User");
lv_obj_set_style_bg_color(ui_User, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_User, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_User, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_User, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_User, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AreaCurrentUser = lv_textarea_create(ui_User);
lv_obj_set_width( ui_AreaCurrentUser, lv_pct(100));
lv_obj_set_height( ui_AreaCurrentUser, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_AreaCurrentUser, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_AreaCurrentUser,"Current user password");
lv_textarea_set_one_line(ui_AreaCurrentUser,true);
lv_textarea_set_password_mode(ui_AreaCurrentUser, true);



ui_AreaNewUser = lv_textarea_create(ui_User);
lv_obj_set_width( ui_AreaNewUser, lv_pct(100));
lv_obj_set_height( ui_AreaNewUser, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaNewUser, 1 );
lv_obj_set_y( ui_AreaNewUser, -23 );
lv_obj_set_align( ui_AreaNewUser, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_AreaNewUser,"New user password");
lv_textarea_set_one_line(ui_AreaNewUser,true);
lv_textarea_set_password_mode(ui_AreaNewUser, true);



ui_AreaConfirmUser = lv_textarea_create(ui_User);
lv_obj_set_width( ui_AreaConfirmUser, lv_pct(100));
lv_obj_set_height( ui_AreaConfirmUser, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaConfirmUser, 1 );
lv_obj_set_y( ui_AreaConfirmUser, 31 );
lv_obj_set_align( ui_AreaConfirmUser, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_AreaConfirmUser,"Confirm User password");
lv_textarea_set_one_line(ui_AreaConfirmUser,true);
lv_textarea_set_password_mode(ui_AreaConfirmUser, true);



ui_btnChangeUser = lv_btn_create(ui_User);
lv_obj_set_width( ui_btnChangeUser, 60);
lv_obj_set_height( ui_btnChangeUser, 35);
lv_obj_set_align( ui_btnChangeUser, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_btnChangeUser, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnChangeUser, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_btnChangeUser);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Change");

ui_OptionFP = lv_tabview_create(ui_panelSetting, LV_DIR_LEFT, 50);
lv_obj_set_height( ui_OptionFP, 220);
lv_obj_set_width( ui_OptionFP, lv_pct(108));
lv_obj_set_x( ui_OptionFP, 0 );
lv_obj_set_y( ui_OptionFP, 8 );
lv_obj_set_align( ui_OptionFP, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_OptionFP, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_OptionFP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OptionFP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OptionFP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OptionFP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OptionFP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OptionFP, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OptionFP, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_OptionFP), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_OptionFP), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_OptionFP), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_OptionFP), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_OptionFP), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_OptionFP), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_OptionFP), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_Add = lv_tabview_add_tab(ui_OptionFP, "Add");
lv_obj_set_style_bg_color(ui_Add, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Add, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Add, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Add, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Add, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AreaAddFP = lv_textarea_create(ui_Add);
lv_obj_set_width( ui_AreaAddFP, lv_pct(100));
lv_obj_set_height( ui_AreaAddFP, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaAddFP, -1 );
lv_obj_set_y( ui_AreaAddFP, -57 );
lv_obj_set_align( ui_AreaAddFP, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_AreaAddFP,3);
lv_textarea_set_placeholder_text(ui_AreaAddFP,"Add fingerprint ID");
lv_textarea_set_one_line(ui_AreaAddFP,true);
lv_obj_add_flag( ui_AreaAddFP, LV_OBJ_FLAG_HIDDEN );



ui_btnAddFP = lv_btn_create(ui_Add);
lv_obj_set_width( ui_btnAddFP, 60);
lv_obj_set_height( ui_btnAddFP, 35);
lv_obj_set_x( ui_btnAddFP, 0 );
lv_obj_set_y( ui_btnAddFP, -75 );
lv_obj_set_align( ui_btnAddFP, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_btnAddFP, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnAddFP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_label3 = lv_label_create(ui_btnAddFP);
lv_obj_set_width( ui_label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_label3,"Add");
lv_obj_set_style_text_font(ui_label3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Delete = lv_tabview_add_tab(ui_OptionFP, "Delete");
lv_obj_set_style_bg_color(ui_Delete, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Delete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Delete, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Delete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Delete, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AreaDeleteFP = lv_textarea_create(ui_Delete);
lv_obj_set_width( ui_AreaDeleteFP, lv_pct(100));
lv_obj_set_height( ui_AreaDeleteFP, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaDeleteFP, -1 );
lv_obj_set_y( ui_AreaDeleteFP, -57 );
lv_obj_set_align( ui_AreaDeleteFP, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_AreaDeleteFP,3);
lv_textarea_set_placeholder_text(ui_AreaDeleteFP,"Add fingerprint ID");
lv_textarea_set_one_line(ui_AreaDeleteFP,true);



ui_btnDeleteFP = lv_btn_create(ui_Delete);
lv_obj_set_width( ui_btnDeleteFP, 60);
lv_obj_set_height( ui_btnDeleteFP, 35);
lv_obj_set_x( ui_btnDeleteFP, 0 );
lv_obj_set_y( ui_btnDeleteFP, -75 );
lv_obj_set_align( ui_btnDeleteFP, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_btnDeleteFP, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnDeleteFP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_label1 = lv_label_create(ui_btnDeleteFP);
lv_obj_set_width( ui_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_label1,"Add");
lv_obj_set_style_text_font(ui_label1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ShowListFP = lv_tabview_add_tab(ui_OptionFP, "Show list");

ui_AreaShowListFP = lv_textarea_create(ui_ShowListFP);
lv_obj_set_width( ui_AreaShowListFP, lv_pct(100));
lv_obj_set_height( ui_AreaShowListFP, lv_pct(100));
lv_obj_set_align( ui_AreaShowListFP, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_AreaShowListFP,"Placeholder...");



ui_OptionCard = lv_tabview_create(ui_panelSetting, LV_DIR_LEFT, 50);
lv_obj_set_height( ui_OptionCard, 220);
lv_obj_set_width( ui_OptionCard, lv_pct(108));
lv_obj_set_x( ui_OptionCard, 0 );
lv_obj_set_y( ui_OptionCard, 8 );
lv_obj_set_align( ui_OptionCard, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_OptionCard, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_OptionCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OptionCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OptionCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OptionCard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OptionCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OptionCard, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OptionCard, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_OptionCard), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_OptionCard), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_OptionCard), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_OptionCard), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_OptionCard), 1,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_OptionCard), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_OptionCard), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_AddCard = lv_tabview_add_tab(ui_OptionCard, "Add");
lv_obj_set_style_bg_color(ui_AddCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AddCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_AddCard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AddCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AddCard, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AreaAddCard = lv_textarea_create(ui_AddCard);
lv_obj_set_width( ui_AreaAddCard, lv_pct(100));
lv_obj_set_height( ui_AreaAddCard, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaAddCard, -1 );
lv_obj_set_y( ui_AreaAddCard, -57 );
lv_obj_set_align( ui_AreaAddCard, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_AreaAddCard,3);
lv_textarea_set_placeholder_text(ui_AreaAddCard,"Add card ID");
lv_textarea_set_one_line(ui_AreaAddCard,true);



ui_btnAddCard = lv_btn_create(ui_AddCard);
lv_obj_set_width( ui_btnAddCard, 60);
lv_obj_set_height( ui_btnAddCard, 35);
lv_obj_set_x( ui_btnAddCard, 0 );
lv_obj_set_y( ui_btnAddCard, -75 );
lv_obj_set_align( ui_btnAddCard, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_btnAddCard, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnAddCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_label2 = lv_label_create(ui_btnAddCard);
lv_obj_set_width( ui_label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_label2,"Add");
lv_obj_set_style_text_font(ui_label2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DeleteCard = lv_tabview_add_tab(ui_OptionCard, "Delete");
lv_obj_set_style_bg_color(ui_DeleteCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeleteCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_DeleteCard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DeleteCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DeleteCard, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AreaDeleteCardd = lv_textarea_create(ui_DeleteCard);
lv_obj_set_width( ui_AreaDeleteCardd, lv_pct(100));
lv_obj_set_height( ui_AreaDeleteCardd, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_AreaDeleteCardd, -1 );
lv_obj_set_y( ui_AreaDeleteCardd, -57 );
lv_obj_set_align( ui_AreaDeleteCardd, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_AreaDeleteCardd,3);
lv_textarea_set_placeholder_text(ui_AreaDeleteCardd,"Delete card ID");
lv_textarea_set_one_line(ui_AreaDeleteCardd,true);



ui_btnDeleteCard = lv_btn_create(ui_DeleteCard);
lv_obj_set_width( ui_btnDeleteCard, 60);
lv_obj_set_height( ui_btnDeleteCard, 35);
lv_obj_set_x( ui_btnDeleteCard, 0 );
lv_obj_set_y( ui_btnDeleteCard, -75 );
lv_obj_set_align( ui_btnDeleteCard, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_btnDeleteCard, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnDeleteCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_label4 = lv_label_create(ui_btnDeleteCard);
lv_obj_set_width( ui_label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_label4,"Delete");
lv_obj_set_style_text_font(ui_label4, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ShowListCard = lv_tabview_add_tab(ui_OptionCard, "Show list");

ui_AreaShowListCard = lv_textarea_create(ui_ShowListCard);
lv_obj_set_width( ui_AreaShowListCard, lv_pct(100));
lv_obj_set_height( ui_AreaShowListCard, lv_pct(100));
lv_obj_set_align( ui_AreaShowListCard, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_AreaShowListCard,"Placeholder...");



ui_KeyboardDisplay = lv_keyboard_create(ui_Screen3);
lv_keyboard_set_mode(ui_KeyboardDisplay,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_height( ui_KeyboardDisplay, 200);
lv_obj_set_width( ui_KeyboardDisplay, lv_pct(100));
lv_obj_set_align( ui_KeyboardDisplay, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_KeyboardDisplay, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_AreaDisplay = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_AreaDisplay, lv_pct(70));
lv_obj_set_height( ui_AreaDisplay, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_AreaDisplay, 0 );
lv_obj_set_y( ui_AreaDisplay, 75 );
lv_obj_set_align( ui_AreaDisplay, LV_ALIGN_TOP_MID );
lv_textarea_set_max_length(ui_AreaDisplay,12);
lv_textarea_set_one_line(ui_AreaDisplay,true);
lv_obj_add_flag( ui_AreaDisplay, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_letter_space(ui_AreaDisplay, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_AreaDisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AreaDisplay, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_AreaPopupSetting = lv_textarea_create(ui_Screen3);
lv_obj_set_height( ui_AreaPopupSetting, 80);
lv_obj_set_width( ui_AreaPopupSetting, lv_pct(70));
lv_obj_set_align( ui_AreaPopupSetting, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_AreaPopupSetting,"Notify!");
lv_obj_set_style_text_align(ui_AreaPopupSetting, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AreaPopupSetting, lv_color_hex(0xF90613), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AreaPopupSetting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AreaPopupSetting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AreaPopupSetting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AreaPopupSetting, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AreaPopupSetting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_add_flag( ui_AreaPopupSetting, LV_OBJ_FLAG_HIDDEN );



lv_obj_add_event_cb(ui_PasswordbtnSetting, ui_event_PasswordbtnSetting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FPbtnSetting, ui_event_FPbtnSetting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CardbtnSetting, ui_event_CardbtnSetting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HomebtnSetting, ui_event_HomebtnSetting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaCurrentAdmin, ui_event_AreaCurrentAdmin, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaNewAdmin, ui_event_AreaNewAdmin, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaConfirmAdmin, ui_event_AreaConfirmAdmin, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnChangebtn, ui_event_btnChangebtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Admin, ui_event_Admin, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaCurrentUser, ui_event_AreaCurrentUser, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaNewUser, ui_event_AreaNewUser, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaConfirmUser, ui_event_AreaConfirmUser, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnChangeUser, ui_event_btnChangeUser, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_User, ui_event_User, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaAddFP, ui_event_AreaAddFP, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnAddFP, ui_event_btnAddFP, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Add, ui_event_Add, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaDeleteFP, ui_event_AreaDeleteFP, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnDeleteFP, ui_event_btnDeleteFP, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Delete, ui_event_Delete, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ShowListFP, ui_event_ShowListFP, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaAddCard, ui_event_AreaAddCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnAddCard, ui_event_btnAddCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AddCard, ui_event_AddCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AreaDeleteCardd, ui_event_AreaDeleteCardd, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnDeleteCard, ui_event_btnDeleteCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DeleteCard, ui_event_DeleteCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ShowListCard, ui_event_ShowListCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_OptionCard, ui_event_OptionCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panelSetting, ui_event_panelSetting, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardDisplay,ui_AreaDisplay);

}
