// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: GUI_v1

#include "../ui.h"

void ui_screenCardShow_screen_init(void)
{
ui_screenCardShow = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenCardShow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelCardShow = lv_obj_create(ui_screenCardShow);
lv_obj_set_width( ui_PanelCardShow, lv_pct(100));
lv_obj_set_height( ui_PanelCardShow, lv_pct(100));
lv_obj_set_align( ui_PanelCardShow, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelCardShow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelCardShow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelCardShow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label36 = lv_label_create(ui_PanelCardShow);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label36, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label36,"Card List");
lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelShowCard = lv_obj_create(ui_screenCardShow);
lv_obj_set_height( ui_panelShowCard, 275);
lv_obj_set_width( ui_panelShowCard, lv_pct(100));
lv_obj_set_align( ui_panelShowCard, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_panelShowCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelShowCard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelShowCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelShowCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnBackShowCard = lv_btn_create(ui_screenCardShow);
lv_obj_set_width( ui_btnBackShowCard, 50);
lv_obj_set_height( ui_btnBackShowCard, 23);
lv_obj_set_x( ui_btnBackShowCard, 5 );
lv_obj_set_y( ui_btnBackShowCard, -5 );
lv_obj_set_align( ui_btnBackShowCard, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_btnBackShowCard, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnBackShowCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnBackShowCard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnBackShowCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnBackShowCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackFinger7 = lv_label_create(ui_btnBackShowCard);
lv_obj_set_width( ui_BackFinger7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackFinger7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BackFinger7, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackFinger7,"Back");
lv_obj_set_style_text_color(ui_BackFinger7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackFinger7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackFinger7, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnHomeShowCard = lv_btn_create(ui_screenCardShow);
lv_obj_set_width( ui_btnHomeShowCard, 50);
lv_obj_set_height( ui_btnHomeShowCard, 23);
lv_obj_set_x( ui_btnHomeShowCard, -7 );
lv_obj_set_y( ui_btnHomeShowCard, -5 );
lv_obj_set_align( ui_btnHomeShowCard, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_btnHomeShowCard, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnHomeShowCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnHomeShowCard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnHomeShowCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnHomeShowCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackHomeAddFinger5 = lv_label_create(ui_btnHomeShowCard);
lv_obj_set_width( ui_BackHomeAddFinger5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackHomeAddFinger5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BackHomeAddFinger5, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackHomeAddFinger5,"Home");
lv_obj_set_style_text_color(ui_BackHomeAddFinger5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackHomeAddFinger5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackHomeAddFinger5, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_areaShowCard = lv_textarea_create(ui_panelShowCard);
lv_obj_set_width( ui_areaShowCard, lv_pct(95));
lv_obj_set_height( ui_areaShowCard, 220);
lv_obj_set_x( ui_areaShowCard, 0 );
lv_obj_set_y( ui_areaShowCard, 0 );
lv_obj_set_align( ui_areaShowCard, LV_ALIGN_CENTER );
// lv_textarea_set_text(ui_areaShowCard,"Card Count : 20");
lv_obj_set_style_text_color(ui_areaShowCard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_areaShowCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_areaShowCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_areaShowCard, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_areaShowCard, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_areaShowCard, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_areaShowCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_areaShowCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_areaShowCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



lv_obj_add_event_cb(ui_btnBackShowCard, ui_event_btnBackShowCard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnHomeShowCard, ui_event_btnHomeShowCard, LV_EVENT_ALL, NULL);

}
