// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: GUI_v1

#ifndef _GUI_V1_UI_H
#define _GUI_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_rootpanel( lv_event_t * e);
extern lv_obj_t *ui_rootpanel;
extern lv_obj_t *ui_AreaPWHome;
void ui_event_Unlockbtn( lv_event_t * e);
extern lv_obj_t *ui_Unlockbtn;
void ui_event_Settingbtn( lv_event_t * e);
extern lv_obj_t *ui_Settingbtn;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_AreaPopup;
extern lv_obj_t *ui_KeyboardPWHome;
void ui_event_PressedOkPW( lv_event_t *e);
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
void ui_event_panelSetting( lv_event_t * e);
extern lv_obj_t *ui_panelSetting;
void ui_event_PasswordbtnSetting( lv_event_t * e);
extern lv_obj_t *ui_PasswordbtnSetting;
void ui_event_FPbtnSetting( lv_event_t * e);
extern lv_obj_t *ui_FPbtnSetting;
void ui_event_CardbtnSetting( lv_event_t * e);
extern lv_obj_t *ui_CardbtnSetting;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
void ui_event_HomebtnSetting( lv_event_t * e);
extern lv_obj_t *ui_HomebtnSetting;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_OptionPassword;
void ui_event_Admin( lv_event_t * e);
extern lv_obj_t *ui_Admin;
void ui_event_AreaCurrentAdmin( lv_event_t * e);
extern lv_obj_t *ui_AreaCurrentAdmin;
void ui_event_AreaNewAdmin( lv_event_t * e);
extern lv_obj_t *ui_AreaNewAdmin;
void ui_event_AreaConfirmAdmin( lv_event_t * e);
extern lv_obj_t *ui_AreaConfirmAdmin;
void ui_event_btnChangebtn( lv_event_t * e);
extern lv_obj_t *ui_btnChangebtn;
extern lv_obj_t *ui_Label1;
void ui_event_User( lv_event_t * e);
extern lv_obj_t *ui_User;
void ui_event_AreaCurrentUser( lv_event_t * e);
extern lv_obj_t *ui_AreaCurrentUser;
void ui_event_AreaNewUser( lv_event_t * e);
extern lv_obj_t *ui_AreaNewUser;
void ui_event_AreaConfirmUser( lv_event_t * e);
extern lv_obj_t *ui_AreaConfirmUser;
void ui_event_btnChangeUser( lv_event_t * e);
extern lv_obj_t *ui_btnChangeUser;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_OptionFP;
void ui_event_Add( lv_event_t * e);
extern lv_obj_t *ui_Add;
void ui_event_AreaAddFP( lv_event_t * e);
extern lv_obj_t *ui_AreaAddFP;
void ui_event_btnAddFP( lv_event_t * e);
extern lv_obj_t *ui_btnAddFP;
extern lv_obj_t *ui_label3;
void ui_event_Delete( lv_event_t * e);
extern lv_obj_t *ui_Delete;
void ui_event_AreaDeleteFP( lv_event_t * e);
extern lv_obj_t *ui_AreaDeleteFP;
void ui_event_btnDeleteFP( lv_event_t * e);
extern lv_obj_t *ui_btnDeleteFP;
extern lv_obj_t *ui_label1;
void ui_event_ShowListFP( lv_event_t * e);
extern lv_obj_t *ui_ShowListFP;
extern lv_obj_t *ui_AreaShowListFP;
void ui_event_OptionCard( lv_event_t * e);
extern lv_obj_t *ui_OptionCard;
void ui_event_AddCard( lv_event_t * e);
extern lv_obj_t *ui_AddCard;
void ui_event_AreaAddCard( lv_event_t * e);
extern lv_obj_t *ui_AreaAddCard;
void ui_event_btnAddCard( lv_event_t * e);
extern lv_obj_t *ui_btnAddCard;
extern lv_obj_t *ui_label2;
void ui_event_DeleteCard( lv_event_t * e);
extern lv_obj_t *ui_DeleteCard;
void ui_event_AreaDeleteCardd( lv_event_t * e);
extern lv_obj_t *ui_AreaDeleteCardd;
void ui_event_btnDeleteCard( lv_event_t * e);
extern lv_obj_t *ui_btnDeleteCard;
extern lv_obj_t *ui_label4;
void ui_event_ShowListCard( lv_event_t * e);
extern lv_obj_t *ui_ShowListCard;
extern lv_obj_t *ui_AreaShowListCard;
extern lv_obj_t *ui_KeyboardDisplay;
extern lv_obj_t *ui_AreaDisplay;
extern lv_obj_t *ui_AreaPopupSetting;
// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
extern lv_obj_t *ui_ScreenSetting;
extern lv_obj_t *ui_Panel1;
void ui_event_HomeOptionbtn( lv_event_t * e);
extern lv_obj_t *ui_HomeOptionbtn;
void ui_event_PWOptionbtn( lv_event_t * e);
extern lv_obj_t *ui_PWOptionbtn;
void ui_event_FPOptionbtn( lv_event_t * e);
extern lv_obj_t *ui_FPOptionbtn;
void ui_event_CardOptionbtn( lv_event_t * e);
extern lv_obj_t *ui_CardOptionbtn;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_iconunlock_png);   // assets\iconUnlock.png
LV_IMG_DECLARE( ui_img_iconsetting_png);   // assets\iconSetting.png
LV_IMG_DECLARE( ui_img_iconpassword_png);   // assets\iconPassword.png
LV_IMG_DECLARE( ui_img_iconfinger_png);   // assets\iconFinger.png
LV_IMG_DECLARE( ui_img_iconcard_png);   // assets\iconCard.png
LV_IMG_DECLARE( ui_img_iconhome_png);   // assets\iconHome.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
