// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: GUI_v1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void isSettingMode(lv_event_t * e);
void callFuncChangeAdminPW(lv_event_t * e);
void callFuncChangeUserPW(lv_event_t * e);
void callFuncAddFP(lv_event_t * e);
void callFuncDeleteFP(lv_event_t * e);
void callFuncShowListFP(lv_event_t * e);
void callFuncAddCard(lv_event_t * e);
void callFuncDeleteCard(lv_event_t * e);
void callFuncShowListCard(lv_event_t * e);
void callFuncCheckPW(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
