// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: GUI_v1

#include "ui.h"

void isSettingMode(lv_event_t * e)
{
	// Your code here
}

void callFuncChangeAdminPW(lv_event_t * e)
{
	// Your code here
}

void callFuncChangeUserPW(lv_event_t * e)
{
	// Your code here
}

// void callFuncAddFP(lv_event_t * e)
// {
// 	// Your code here
// }

void callFuncDeleteFP(lv_event_t * e)
{
	// Your code here
}

void callFuncShowListFP(lv_event_t * e)
{
	// Your code here
}

void callFuncAddCard(lv_event_t * e)
{
	// Your code here
}

// void callFuncDeleteCard(lv_event_t * e)
// {
// 	// Your code here
// }

void callFuncShowListCard(lv_event_t * e)
{
	// Your code here
}
