// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: GUI_v1

#include "ui.h"

void isSettingMode(lv_event_t * e)
{
	// Your code here
}


// void callFuncAddFP(lv_event_t * e)
// {
// 	// Your code here
// }

// void callFuncRestoreFP(lv_event_t * e)
// {
// 	// Your code here
// }

// void callFuncShowFP(lv_event_t * e)
// {
// 	// Your code here
// }

// void callFuncDeleteCard(lv_event_t * e)
// {
// 	// Your code here
// }

void callFuncAddCard(lv_event_t * e)
{
	// Your code here
}

void callFuncRestoreCard(lv_event_t * e)
{
	// Your code here
}

void callFuncShowCard(lv_event_t * e)
{
	// Your code here
}

void callFuncChangePW(lv_event_t * e)
{
	// Your code here
}
